export default function PrivacyPolicyPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-10 text-foreground">
      <h1 className="text-2xl font-semibold">Privacy Policy</h1>
      <p className="mt-4 text-sm text-muted-foreground">
        Last updated: February 16, 2026
      </p>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">1. Who We Are</h2>
        <p>
          This mobile application ("Task Bored") is operated by Herman Schroeder Mans.
        </p>
        <p>Contact email: hsmans0601@gmail.com</p>
        <p>Country of operation: South Africa</p>
        <p>
          If you have questions about this Privacy Policy, contact us using the email above.
        </p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">2. Information We Collect</h2>
        <p>We collect the following information when you use the App:</p>
        <h3 className="font-semibold">Account Information</h3>
        <ul className="list-disc space-y-1 pl-5">
          <li>Email address</li>
          <li>Profile information you provide</li>
          <li>User ID generated by our authentication system</li>
        </ul>
        <h3 className="font-semibold">Workspace &amp; Content Data</h3>
        <ul className="list-disc space-y-1 pl-5">
          <li>Boards, tasks, issues, and comments</li>
          <li>Attachments or metadata you upload</li>
          <li>Activity history related to your workspace</li>
        </ul>
        <h3 className="font-semibold">Integration Data (If Enabled)</h3>
        <ul className="list-disc space-y-1 pl-5">
          <li>GitHub repository metadata (when you authorize access)</li>
          <li>Integration tokens required to provide requested features</li>
        </ul>
        <h3 className="font-semibold">Technical &amp; Usage Data</h3>
        <ul className="list-disc space-y-1 pl-5">
          <li>Device type and operating system</li>
          <li>App version</li>
          <li>Log data for troubleshooting and security</li>
          <li>Basic usage analytics (if enabled in your deployment)</li>
        </ul>
        <p>We do not sell personal data.</p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">3. How We Use Your Information</h2>
        <p>We use collected data to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Authenticate users</li>
          <li>Provide collaboration and task management features</li>
          <li>Store and sync boards and issues</li>
          <li>Enable authorized integrations (such as GitHub)</li>
          <li>Detect abuse or unauthorized access</li>
          <li>Maintain service performance and security</li>
          <li>Provide user support</li>
        </ul>
        <p>We process only the minimum data necessary to operate the App.</p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">4. Legal Basis (POPIA Compliance)</h2>
        <p>
          Where applicable, personal information is processed in accordance with POPIA principles,
          including:
        </p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Accountability</li>
          <li>Purpose limitation</li>
          <li>Data minimization</li>
          <li>Information quality</li>
          <li>Transparency</li>
          <li>Security safeguards</li>
        </ul>
        <p>Processing is based on:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Your consent</li>
          <li>Performance of a contract (providing the App)</li>
          <li>Legitimate interests related to security and service improvement</li>
        </ul>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">5. Third-Party Service Providers</h2>
        <p>We use trusted third-party processors to operate the App:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Supabase (authentication and database hosting)</li>
          <li>GitHub (repository integration, if authorized by you)</li>
        </ul>
        <p>
          These providers process data on our behalf and under appropriate security safeguards.
        </p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">6. International Data Transfers</h2>
        <p>
          Your data may be transferred to and stored in countries outside your country of residence.
        </p>
        <p>These jurisdictions may have different data protection laws.</p>
        <p>We ensure appropriate safeguards are in place for such transfers.</p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">7. Data Retention</h2>
        <p>We retain data only as long as necessary:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Account profile data: retained while your account is active</li>
          <li>Boards, tasks, and comments: retained while your workspace is active</li>
          <li>Security and audit logs: retained for up to 12 months</li>
          <li>Support records and deletion requests: retained for up to 24 months</li>
        </ul>
        <p>When data is no longer required, it is securely deleted.</p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">8. Data Security</h2>
        <p>
          We implement reasonable technical and organizational safeguards, including:
        </p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Encrypted HTTPS connections for all data transmission</li>
          <li>Secure storage of authentication tokens on device</li>
          <li>Access controls restricting database access</li>
          <li>Monitoring and logging for suspicious activity</li>
        </ul>
        <p>
          No system can be guaranteed 100% secure, but we take reasonable steps to protect your
          data.
        </p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">9. Account Deletion</h2>
        <p>You may request deletion of your account and associated data by:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Using the in-app account deletion feature</li>
          <li>Following the documented process on the Account Deletion page</li>
          <li>Contacting us at the email listed above</li>
        </ul>
        <p>
          Upon verified request, your personal data will be deleted in accordance with applicable
          law.
        </p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">10. Your Rights</h2>
        <p>Depending on your jurisdiction, you may:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Request access to your personal data</li>
          <li>Request correction of inaccurate data</li>
          <li>Request deletion of your data</li>
          <li>Object to certain processing</li>
          <li>Withdraw consent where applicable</li>
        </ul>
        <p>Requests can be submitted via email.</p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">11. Children's Privacy</h2>
        <p>
          The App is not directed at children under the age of 13.
        </p>
        <p>We do not knowingly collect personal data from children.</p>
        <p>
          If we become aware that a child has provided personal data, we will delete it.
        </p>
      </section>

      <section className="mt-8 space-y-3 text-sm leading-6">
        <h2 className="text-lg font-semibold">12. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time.
        </p>
        <p>Updates will be reflected by revising the "Last updated" date.</p>
        <p>Continued use of the App constitutes acceptance of the updated policy.</p>
      </section>
    </main>
  );
}
